Avoid brew doctor issue with Ruby file in root directory
snyk/homebrew-tap pull request #7
Opened 2020-08-09 09:40 UTC by garethr

Fixes #6

2020-11-25 02:10 UTC, affan0078 requested changes

2020-11-25 02:10 UTC, affan0078 commented on script/render.rb
> -template = File.read("template.erb")
script/render.rb

2021-02-07 04:47 UTC, soberich commented
Same.
Why is this hanging?

2021-03-23 05:49 UTC, rmkanda commented
@pkey @snyksec  Can you check this?

2021-03-23 08:35 UTC, merged